// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-CpLCtOeWTPTwvREnzqbR0xiFtjI6GTw',
    appId: '1:473086017233:web:a44698a5f59baf1092cff0',
    messagingSenderId: '473086017233',
    projectId: 'booked-dcdf1',
    authDomain: 'booked-dcdf1.firebaseapp.com',
    storageBucket: 'booked-dcdf1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDv-HiM4TE0MYQRYWhcXN7KOCrSvt67YBk',
    appId: '1:473086017233:android:57622924e97b798892cff0',
    messagingSenderId: '473086017233',
    projectId: 'booked-dcdf1',
    storageBucket: 'booked-dcdf1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDYo3DxG1aoYOtxV5dOLBdjKJ9hhN-DK4s',
    appId: '1:473086017233:ios:efb084d1bada998c92cff0',
    messagingSenderId: '473086017233',
    projectId: 'booked-dcdf1',
    storageBucket: 'booked-dcdf1.appspot.com',
    iosClientId: '473086017233-cl7428df8kghn29u5q4kluml8ikff0jg.apps.googleusercontent.com',
    iosBundleId: 'com.example.bookedWebappV1',
  );
}
